name: CI/CD
on:
  push:
    branches:
     -master
  pull_request:
    branches:
      -master  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: action/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
         node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Tests 
        run: npm run test -- --no-watch --code-coverage
      -name: Runtests with code coverage
        uses: coactions/setup-xvfb@v1
        run: npm run test-- --no-watch --code-coverage