name: CI/CD
on:
    push:
        branches:
            -master
            -develop
    pull_request:
        branches:
            -master
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -name: Checkout code
            uses: action/checkout@v2

            -name: Setup Node
            uses: action/setuo-node@v2
            with:
                node-version: 18.x

            -name: Install dependencies
            run: npm install

            -name: Tests
            run: npm run test -- --no-watch --code-coverage